name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC
  workflow_dispatch:     # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Gera a cobrinha animada
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: GustavoMottaSchmitel
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Faz commit e push do SVG
      - name: Push to GitHub
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output   # ramo onde a cobrinha será salva
          folder: dist     # pasta gerada pela action
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
